### PR TITLE
Fix typo on website

### PR DESCRIPTION
**Pull request by Klaudioz**
Signed-off-by: Klaudioz <klaudioz@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
you don't want to fix it?  ;-)

**Comment by duglin** [comment]
very few people have write permission to this (and the 'spec') repos - everything is done thru a PR/review process. So go head and submit the PR and then we'll get it reviewed/merged.

**Comment by Klaudioz** [comment]
Thank you. My doubt is how to do it in the website and being able to add `git commit -s`. I tried it putting it in the comment here but it didn't work.

image

**Comment by duglin** [comment]
I've never been able to get it to work via the website - I always use the command line

**Pull request closed without merging**
