### PR TITLE
Adding Adobe I/O Events in Integrations

### PR DESCRIPTION
**Pull request by kgera**
Adding Adobe I/O Events in Integrations.
Signed-off-by: Kanika Gera <kgera@adobe.com>

### CODE REVIEW

**Comment by duglin** [comment]
I think the indentation is off and can you add it so the list of products are still alphabetical?

**Comment by kgera** [comment]
@duglin I have made changes to indentation and alphabetical order.

**Comment by duglin** [comment]
thanks - can you sign your commits?

**Comment by kgera** [comment]
Creating new request which is signed.

**Pull request closed without merging**
