### PR TITLE
Add commercetools integration

### PR DESCRIPTION
**Pull request by cneijenhuis**
In case you're wondering: The lowercased name is not a typo... 😉 

Signed-off-by: Christoph Neijenhuis <christoph.neijenhuis@commercetools.de>

### CODE REVIEW

**Comment by duglin** [comment]
@cneijenhuis sorry for the delay. The logo doesn't seem to load for me - is the URL correct? It seems to point to the website instead of a logo

**Comment by cneijenhuis** [comment]
The logo file is part of the PR... I thought that just the filename is enough to link it? It's the syntax all other entries use as well.

**Comment by duglin** [comment]
hmm weird - so I'm gonna merge and see what happens :-)

**Comment by cneijenhuis** [comment]
Ah damn, I put it in the wrong folder - should have put it into `logos/integrations`, not only `logos` :(

Sorry!

**Comment by duglin** [comment]
Ah, it needs to go into  the "integrations" dir!

**Comment by duglin** [comment]
you beat me to it!

**Pull request merged**
