### PR TITLE
Adding Debezium to integrations

### PR DESCRIPTION
**Pull request by gunnarmorling**
Hey @duglin, adding Debezium to the list of integrations as per your suggestion. Thanks!

### CODE REVIEW

**Comment by duglin** [comment]
@gunnarmorling thanks!! Can you sign your commit so the DCO checker is happy?

**Comment by gunnarmorling** [comment]
Ah, of course. Done and force-pushed.

**Comment by duglin** [comment]
thanks!

**Comment by gunnarmorling** [comment]
Thank _you_ for the quick turnaround!

>

**Pull request merged**
