### PR TITLE
Add VMware Event Broker Appliance as a CloudEvents user

### PR DESCRIPTION
**Pull request by evankanderson**
I was talking with @lamw the other day, and I realized that the VEBA logo isn't present on the CloudEvents integrations page, despite the work that team is doing to bring CloudEvents to the datacenter automation audience.

### CODE REVIEW

**Comment by duglin** [comment]
@evankanderson where is this logo referenced from?

**Comment by evankanderson** [comment]
The file that I forgot to stage...

**Comment by duglin** [comment]
LOL that looks much better - thanks

**Pull request merged**
