### PR TITLE
WIP: New template

### PR DESCRIPTION
**Pull request by slickplaid**
Using `hugo-stellar-theme` and some customized colors. Moved the markdown into the `config.toml` file because I couldn't get some of the features to work properly from the simplistic markdown+meta parameters.

Todo:
* make sure the icons are the ones that should be used
* markdown posts are not supported in this template, but we can relatively easily add the new functionality
* The font selection on the buttons could be tweaked. It's a little hard to read sometimes, depending on your OS and browser.
* possibly think of something better for the footer area on the left side content. It's just repeated from the subtitle
* once the design is checked off, I'll clean up the code and remove any extraneous or commented out html/config

Hugo is pretty simplistic and difficult to add anything too fancy. If this site needs more complexity, I'd recommend moving it to a different ssg.

### CODE REVIEW

**Comment by barkerd427** [comment]
I may have fixed the preview now, but we need something to kick it off again.

**Comment by barkerd427** [comment]
Can we also get rid of the contents directory?

**Comment by slickplaid** [comment]
done and done

**Comment by barkerd427** [comment]
What happened to travis?

**Comment by dankohn** [comment]
@caniszczyk Can set you up with a Netlify account to publish, if you want it. It's what K8s uses.

**Comment by barkerd427** [comment]
@dankohn, I created this with my own account on both Travis and Netlify, but I'm happy to convert them both if we have a common account or something.

**Comment by barkerd427** [comment]
@duglin, this is a PR for our updated website design. Do we want to discuss this in the Thursday meeting?

**Pull request merged**
