### PR TITLE
add v1.0.2 release info

### LINKED ISSUE #64: CloudEvents v1.0.2 release
It would be necessary to add last spec release v1.0.2 in the releases section in the home page.

### PR DESCRIPTION
**Pull request by duglin**
Fixes #64 

Signed-off-by: Doug Davis <dug@microsoft.com>

### CODE REVIEW

**Comment by dbaldwin-s1** [comment]
LGTM

**Comment by markpeek** [comment]
Overall looks good. Two comments:

- This statement `Note that this release is compatible with the existing CloudEvents v1.0 specification.` is part of the 1.0.1 text but not 1.0.2. I'd think the guarantee is both are compatible or else we would have released a 2.0.
- Could bullet the 1.0.2 change list to highlight better.

**Comment by duglin** [comment]
@markpeek see if it looks better now

**Comment by markpeek** [comment]
LGTM

**Comment by duglin** [comment]
great - thanks for the review

**Pull request merged**
